export type {
  Adapter,
  AdapterCompatibility,
  AdapterPluginIdentity,
  ApplyCapability,
  ApplyContext,
  ApplyResult,
  AttributeProjection,
  OpenContext,
  Operation,
  PlanningCapability,
  PlanContext,
  ReadCapability,
  ResourceHandle,
  RootRequest,
  SourceDescriptor,
  MountCapability,
  MountSourceDescriptor,
} from "./adapter.js";
export { adapterCompatibility, validateAdapter } from "./adapter.js";
export { PluginError, definePluginManifest, registerPlugins } from "./plugin.js";
export type {
  PluginAliases,
  PluginContributionManifest,
  PluginContributions,
  PluginDiffProviderContribution,
  PluginFunctionContribution,
  PluginManifest,
  PluginModule,
  PluginMountContribution,
  PluginOperationContribution,
  PluginOptimizerEquivalence,
  PluginOptimizerRule,
  PluginPolicy,
  PluginPower,
  PluginPredicateContribution,
  PluginRegistry,
  PluginRendererContribution,
  PluginResolverContribution,
} from "./plugin.js";
export {
  applyChangePlan,
  deserializeChangePlan,
  planOperations,
  renderChangePlan,
  resourceIdentity,
  serializeChangePlan,
} from "./change.js";
export type {
  ApplyChangePlanOptions,
  ApplyGroupResult,
  ApplyGroupStatus,
  Change,
  ChangePlan,
  ChangePlanApplyResult,
  ChangePrecondition,
  ChangeRegion,
  ChangeRisk,
  ChangeTransaction,
  DeserializeChangePlanOptions,
  PlanAdapterIdentity,
  PlannedChange,
  PlannedOperation,
  PlanResourceIdentity,
  RenderChangePlanOptions,
  TextChangePreview,
  TransactionGroup,
} from "./change.js";
export { defineDiagnostic } from "./diagnostic.js";
export type {
  Diagnostic,
  DiagnosticLocation,
  DiagnosticSeverity,
} from "./diagnostic.js";
export { DslError, compileDsl, defineDslArgumentSchema, formatDsl, parseDsl } from "./dsl.js";
export type {
  CompiledDsl,
  DslArgumentDefinition,
  DslArgumentSchema,
  DslArguments,
  DslArgumentValue,
  DslBinding,
  DslEnvironment,
  DslExpression,
  DslOptions,
  DslPipeline,
  DslProgram,
  DslStep,
} from "./dsl.js";
export {
  createFilesystemAdapter,
  filesystemCreate,
  filesystemMove,
  filesystemRemove,
  filesystemWrite,
  fromFilesystem,
} from "./filesystem.js";
export type {
  FilesystemAdapter,
  FilesystemAdapterOptions,
  FilesystemChange,
  FilesystemChangeRisk,
  FilesystemContent,
  FilesystemCreateOperation,
  FilesystemMoveOperation,
  FilesystemNodeKind,
  FilesystemOperation,
  FilesystemOperationKind,
  FilesystemPrecondition,
  FilesystemRemoveOperation,
  FilesystemSource,
  FilesystemStatistics,
  FilesystemWriteOperation,
} from "./filesystem.js";
export {
  createJsonAdapter,
  jsonInsertArrayItem,
  jsonInsertProperty,
  jsonRemoveArrayItem,
  jsonRemoveProperty,
  jsonReplaceValue,
  mountJson,
  mountJsonTextHandle,
} from "./json.js";
export type {
  JsonAdapter,
  JsonChange,
  JsonInsertArrayItemOperation,
  JsonInsertPropertyOperation,
  JsonMountOptions,
  JsonNodeKind,
  JsonOperation,
  JsonOperationKind,
  JsonPatchPayload,
  JsonPrecondition,
  JsonPrimitive,
  JsonRemoveArrayItemOperation,
  JsonRemovePropertyOperation,
  JsonReplaceValueOperation,
  JsonStatistics,
  JsonTextMountSource,
  JsonValue,
} from "./json.js";
export {
  createMarkdownAdapter,
  fromMarkdown,
  markdownReplaceSection,
  markdownSetHeading,
  mountMarkdown,
} from "./markdown.js";
export type {
  MarkdownAdapter,
  MarkdownAdapterOptions,
  MarkdownChange,
  MarkdownMountOptions,
  MarkdownNodeKind,
  MarkdownOperation,
  MarkdownOperationKind,
  MarkdownPatchPayload,
  MarkdownPrecondition,
  MarkdownReplaceSectionOperation,
  MarkdownSetHeadingOperation,
  MarkdownSource,
  MarkdownStatistics,
  MarkdownTreeView,
} from "./markdown.js";
export {
  assertNamespace,
  assertNamespacedName,
  defineEdge,
  defineNodeSnapshot,
  defineResource,
} from "./model.js";
export type {
  AttributeValue,
  Edge,
  EdgeName,
  EdgeRequest,
  EdgeRole,
  NamespacedName,
  NodeHandle,
  NodeId,
  NodeKind,
  NodeSnapshot,
  OperationKind,
  Origin,
  Resource,
  Revision,
  Scalar,
  Selection,
  SelectionOrdering,
  SourceRange,
} from "./model.js";
export { createInMemoryAdapter } from "./memory.js";
export type {
  InMemoryAdapter,
  InMemoryFixture,
  InMemoryStatistics,
} from "./memory.js";
export {
  Query,
  capture,
  count,
  distinct,
  filter,
  flatMap,
  fromAdapter,
  fromValues,
  groupBy,
  join,
  project,
  sort,
  take,
  traverse,
} from "./query.js";
export type {
  CaptureMap,
  EmptyCaptures,
  ExecuteOptions,
  Group,
  JoinOptions,
  LogicalPlan,
  MaybePromise,
  NavigableNodeHandle,
  PhysicalPlan,
  QueryExplanation,
  QueryOperator,
  TraverseOptions,
} from "./query.js";
export { SelectorError, parseSelector, select, selectFrom, validateSelector } from "./selector.js";
export type {
  SelectorAttributePredicate,
  SelectorCaptureReference,
  SelectorCombinator,
  SelectorCompound,
  SelectorLiteral,
  SelectorOperand,
  SelectorOptions,
  SelectorProgram,
  SelectorPseudo,
  SelectorRegularExpression,
  SelectorSchema,
  SelectorSequence,
  SelectorSourceMode,
  SelectorStep,
} from "./selector.js";
export { createSqlAdapter, fromSqlRows, sqlDeleteRows, sqlUpdateRows } from "./sql.js";
export type {
  SqlAdapter,
  SqlAdapterOptions,
  SqlAggregate,
  SqlCatalog,
  SqlChange,
  SqlChangePayload,
  SqlClient,
  SqlColumnCatalog,
  SqlColumnReference,
  SqlColumnSelection,
  SqlColumnType,
  SqlComparisonOperator,
  SqlCompiledQuery,
  SqlDeleteRowsOperation,
  SqlJoin,
  SqlMutationTarget,
  SqlOperation,
  SqlOptimisticConcurrency,
  SqlOrder,
  SqlPredicate,
  SqlQueryRequest,
  SqlRelationCatalog,
  SqlRelationEndpoint,
  SqlRow,
  SqlRowSource,
  SqlSchemaCatalog,
  SqlStatementResult,
  SqlStatistics,
  SqlTableCatalog,
  SqlTableReference,
  SqlTransactionConcurrency,
  SqlUpdateRowsOperation,
  SqlValue,
} from "./sql.js";
export {
  createTypeScriptAdapter,
  mountTypeScript,
  typeScriptRenameSymbol,
  typeScriptReplaceCall,
} from "./typescript.js";
export type {
  TypeScriptAdapter,
  TypeScriptAdapterOptions,
  TypeScriptChange,
  TypeScriptNodeKind,
  TypeScriptOperation,
  TypeScriptOperationKind,
  TypeScriptPatch,
  TypeScriptPatchPayload,
  TypeScriptPrecondition,
  TypeScriptRenameSymbolOperation,
  TypeScriptReplaceCallOperation,
  TypeScriptStatistics,
} from "./typescript.js";
export { defineAdapterSchema } from "./schema.js";
export type {
  AdapterCapabilities,
  AdapterSchema,
  AttributeSchema,
  Cardinality,
  DynamicAdapterSchema,
  EdgeSchema,
  IdentityGuarantee,
  NodeKindSchema,
  OperationArgumentSchema,
  OperationSchema,
  PushdownCapability,
  ScalarType,
  StaticAdapterSchema,
  TraversalCapability,
  TreeViewSchema,
} from "./schema.js";
