export type {
  Adapter,
  ApplyCapability,
  ApplyContext,
  ApplyResult,
  AttributeProjection,
  OpenContext,
  Operation,
  PlanningCapability,
  PlanContext,
  ReadCapability,
  ResourceHandle,
  RootRequest,
  SourceDescriptor,
} from "./adapter.js";
export {
  applyChangePlan,
  deserializeChangePlan,
  planOperations,
  renderChangePlan,
  resourceIdentity,
  serializeChangePlan,
} from "./change.js";
export type {
  ApplyChangePlanOptions,
  ApplyGroupResult,
  ApplyGroupStatus,
  Change,
  ChangePlan,
  ChangePlanApplyResult,
  ChangePrecondition,
  ChangeRegion,
  ChangeRisk,
  ChangeTransaction,
  DeserializeChangePlanOptions,
  PlanAdapterIdentity,
  PlannedChange,
  PlannedOperation,
  PlanResourceIdentity,
  RenderChangePlanOptions,
  TextChangePreview,
  TransactionGroup,
} from "./change.js";
export { defineDiagnostic } from "./diagnostic.js";
export type {
  Diagnostic,
  DiagnosticLocation,
  DiagnosticSeverity,
} from "./diagnostic.js";
export {
  createFilesystemAdapter,
  filesystemCreate,
  filesystemMove,
  filesystemRemove,
  filesystemWrite,
  fromFilesystem,
} from "./filesystem.js";
export type {
  FilesystemAdapter,
  FilesystemAdapterOptions,
  FilesystemChange,
  FilesystemChangeRisk,
  FilesystemContent,
  FilesystemCreateOperation,
  FilesystemMoveOperation,
  FilesystemNodeKind,
  FilesystemOperation,
  FilesystemOperationKind,
  FilesystemPrecondition,
  FilesystemRemoveOperation,
  FilesystemSource,
  FilesystemStatistics,
  FilesystemWriteOperation,
} from "./filesystem.js";
export {
  createJsonAdapter,
  jsonInsertArrayItem,
  jsonInsertProperty,
  jsonRemoveArrayItem,
  jsonRemoveProperty,
  jsonReplaceValue,
  mountJson,
} from "./json.js";
export type {
  JsonAdapter,
  JsonChange,
  JsonInsertArrayItemOperation,
  JsonInsertPropertyOperation,
  JsonMountOptions,
  JsonNodeKind,
  JsonOperation,
  JsonOperationKind,
  JsonPatchPayload,
  JsonPrecondition,
  JsonPrimitive,
  JsonRemoveArrayItemOperation,
  JsonRemovePropertyOperation,
  JsonReplaceValueOperation,
  JsonStatistics,
  JsonValue,
} from "./json.js";
export {
  assertNamespace,
  assertNamespacedName,
  defineEdge,
  defineNodeSnapshot,
  defineResource,
} from "./model.js";
export type {
  AttributeValue,
  Edge,
  EdgeName,
  EdgeRequest,
  EdgeRole,
  NamespacedName,
  NodeHandle,
  NodeId,
  NodeKind,
  NodeSnapshot,
  OperationKind,
  Origin,
  Resource,
  Revision,
  Scalar,
  Selection,
  SelectionOrdering,
  SourceRange,
} from "./model.js";
export { createInMemoryAdapter } from "./memory.js";
export type {
  InMemoryAdapter,
  InMemoryFixture,
  InMemoryStatistics,
} from "./memory.js";
export {
  Query,
  capture,
  count,
  distinct,
  filter,
  flatMap,
  fromAdapter,
  fromValues,
  groupBy,
  join,
  project,
  sort,
  take,
  traverse,
} from "./query.js";
export type {
  CaptureMap,
  EmptyCaptures,
  ExecuteOptions,
  Group,
  JoinOptions,
  LogicalPlan,
  MaybePromise,
  NavigableNodeHandle,
  PhysicalPlan,
  QueryExplanation,
  QueryOperator,
  TraverseOptions,
} from "./query.js";
export { SelectorError, parseSelector, select, validateSelector } from "./selector.js";
export type {
  SelectorAttributePredicate,
  SelectorCaptureReference,
  SelectorCombinator,
  SelectorCompound,
  SelectorLiteral,
  SelectorOperand,
  SelectorOptions,
  SelectorProgram,
  SelectorPseudo,
  SelectorRegularExpression,
  SelectorSequence,
  SelectorStep,
} from "./selector.js";
export { defineAdapterSchema } from "./schema.js";
export type {
  AdapterCapabilities,
  AdapterSchema,
  AttributeSchema,
  Cardinality,
  DynamicAdapterSchema,
  EdgeSchema,
  IdentityGuarantee,
  NodeKindSchema,
  OperationArgumentSchema,
  OperationSchema,
  PushdownCapability,
  ScalarType,
  StaticAdapterSchema,
  TraversalCapability,
  TreeViewSchema,
} from "./schema.js";
